[tool.poetry]
name = "delta-hub"
version = "0.1.0"
description = ""
authors = ["Shingo OKAWA <shingo.okawa.g.h.c@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
